name: ComBatFed
channels:
  - conda-forge
dependencies:
  - python>=3.10          
  - numpy              
  - pandas              
  - r-base              
  - r-tidyverse
  - pip                   
  - pip:
    - featurecloud